apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: restaurantorder-app
build:
  artifacts:
  - image: weixuantepo/owner
    context: owner
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/order
    context: order
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/create-order
    context: create_order
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/restaurant
    context: restaurant
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/create-restaurant
    context: create_restaurant
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/get-restaurants
    context: get_restaurants
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/notification
    context: notification
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/payment
    context: payment
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile
  - image: weixuantepo/get-orders
    context: get_orders
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/ingress.yaml
    - k8s/mariadb-definition.yaml
    - k8s/mariadb-pv.yaml
    - k8s/owner-definition.yaml
    - k8s/create-order-definition.yaml
    - k8s/restaurant-definition.yaml
    - k8s/order-definition.yaml
    - k8s/create-restaurant-definition.yaml
    - k8s/get-restaurants-definition.yaml
    - k8s/notification-definition.yaml
    - k8s/payment-definition.yaml
    - k8s/get-orders-definition.yaml