apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: restaurantorder-app
build:
  artifacts:
  - image: owner
    context: owner
    sync:
      manual:
        - src: "*.py"
          dest: "."
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/ingress.yaml
    - k8s/mariadb-definition.yaml
    - k8s/mariadb-pv.yaml
    - k8s/owner-definition.yaml
    - k8s/restaurant-definition.yaml
    - k8s/order-definition.yaml

profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: restaurantorder-sg