apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-restaurantorder
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /owner
        backend:
          serviceName: owner-service
          servicePort: 5000
      - path: /restaurant
        backend:
          serviceName: restaurant-service
          servicePort: 5000
      - path: /order
        backend:
          serviceName: order-service
          servicePort: 5000
      - path: /create_order
        backend:
          serviceName: create-order-service
          servicePort: 5000
      - path: /create_restaurant
        backend:
          serviceName: create-restaurant-service
          servicePort: 5000
      - path: /get_restaurants
        backend:
          serviceName: get-restaurants-service
          servicePort: 5000
      - path: /update_order_status
        backend:
          serviceName: update-order-status-service
          servicePort: 5000
        
