apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest_order
  name: rest_order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: gcr.io/restaurantorder-sg/order
        imagePullPolicy: Never
        name: order
        env:
        - name: DB_URL
          value: "mysql+mysqlconnector://root:root@mariadb:3306/order"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: rest_order